name = "Past Life Bone Chip | Valentine Double Teleport Bond"
description = "双人联机专属信物。敲碎阵亡玩家的骨架，必定获得往生骨片，52%概率开出奔赴骨片。\n往生骨片：一次性传送至队友陨落之地（机制对标传送木牌）\n奔赴骨片：无消耗反复传送，实时跟随队友当前位置"
author = "MySelf"
version = "1.0"
api_version = 10
all_clients_require_mod = true
client_only_mod = false
dst_mod = true
configuration_options = {}
